export const HOME = '/'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const PROFILE = '/p/:username'
export const POSTINFO = '/post/:postId'
export const SHARE = '/share'
export const ERROR = '/error'
